// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4z_MPWXtdDuub6Fpz64Or_LrEoxN6dog',
    appId: '1:227320581898:web:6741889e93ea446814b4f3',
    messagingSenderId: '227320581898',
    projectId: 'instagram-backend-d1207',
    authDomain: 'instagram-backend-d1207.firebaseapp.com',
    databaseURL: 'https://instagram-backend-d1207-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-backend-d1207.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMUKoscVD1HBVtncNT1AQseqPYdESjjg',
    appId: '1:227320581898:android:29f63ea4f0ef1a9814b4f3',
    messagingSenderId: '227320581898',
    projectId: 'instagram-backend-d1207',
    databaseURL: 'https://instagram-backend-d1207-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-backend-d1207.appspot.com',
  );
}
